
--- # EC2_AMI Example for creating a basic AMI template from an existing image
- hosts: localhost
  connection: local
  remote_user: root
  become: yes
  gather_facts: no
  vars_files:
    - awscreds
  tasks:
  - name: Basic Provisioning of an AMI from our Instance
    ec2_ami:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      instance_id: i-0fd4eeb8889e17eb0
      wait: no
      name: backup_ami
      tags:
        Name: MyNewAMI
        Service: TestAMIService
    register: instance
