---
- hosts: localhost
  connection: local
  remote_user: root
  become: yes
  gather_facts: no
  vars_files:
    - awscreds
  tasks:
    - name: creating security group
      ec2_group:
         name: ansible_sg
         description: an ansible security group
         tags: {'Name':'ansible_sg'}
         aws_access_key: "{{aws_id}}"
         aws_secret_key: "{{aws_key}}"
         region: "{{aws_region}}"
         vpc_id: vpc-12fc0269
         rules:
           - proto: tcp
             from_port: 0
             to_port: 65535
             cidr_ip: 0.0.0.0/0
      register: res
    - debug: var=res


