
--- # AWS IAM MODULE EXAMPLE
- hosts: localhost
  connection: local
  remote_user: root
  become: yes
  gather_facts: no
  vars_files:
    - awscreds
################# IAM GROUP CREATION ###################
  tasks:
  - name: Creating  IAM Group
    iam:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      iam_type: group 
      name: administrators  
      state: present
########################--policy creation--##################################
  - name: Assign a policy called Admin to the administrators group
    iam_policy:
      iam_type: group    #for user iam_type: user
      iam_name: administrators   #iam_name: gopinadh
      policy_name: Admin
      state: present
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      policy_document: admin_policy.json
##################--IAM USER CREATION--###################################      
  - name: Create a couple of IAM Users and add users into group(administrators)
    iam:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      iam_type: user
      name: "{{ item }}"
      state: present
      groups: administrators
      password: "gopinadh123"
      access_key_state: create
    with_items:
    - tmp1
    - tmp2
    register: output
  - name: Show the JSON Results
    debug: var=output
