
--- # AWS S3 MODULE EXAMPLE
- hosts: localhost
  connection: local
  remote_user: root
  become: yes
  gather_facts: no
  vars_files:
    - awscreds
  tasks:
  - name: Create an S3 Bucket
    aws_s3: 
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      bucket: ansiblebucket2
      mode: create
      permission: public-read-write
    register: create_bucket
  - name: Copy the Files to the Bucket
    aws_s3:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      bucket: ansiblebucket2
      object: /gopinadh/p.b/index.html
      src: /home/devops/gopinadh/p.b/index.html
      mode: put
    register: copy_files
  - name: Output of Creation
    debug: var=create_bucket
  - name: Output of Copy  
    debug: var=copy_files
