---
- hosts: localhost
  connection: local
  remote_user: root
  become: yes
  gather_facts: no
  vars_files:
    - awscreds
  tasks:
    - name: creating snapshot
      ec2_snapshot:
         aws_access_key: "{{aws_id}}"
         aws_secret_key: "{{aws_key}}"
         region: "{{aws_region}}"
         instance_id: i-0f4b6ea6b78f1aa51 
         device_name: /dev/xvda
         description: Taking root volume snapshot
         wait: no
      register: snapshot
    - debug: var=snapshot

                       

