---
- hosts: localhost
  connection: local
  remote_user: root
  become: yes
  gather_facts: no
  vars_files:
    - awscreds
  tasks:
    - name: Create a new volume and attach to running instance
      ec2_vol:
        aws_access_key: "{{aws_id}}"
        aws_secret_key: "{{aws_key}}"
        region: "{{aws_region}}"
        instance: i-0fd4eeb8889e17eb0 
        volume_size: 5
        device_name: sde
      register: volume_result
    - name: set tags in variable
      set_fact:
        vol_id: "{{ volume_result.volume_id }}"
      register: volume_id
######################################################    


                       

